#How long (in ticks) an item fed to a factorymaw lasts.
# Default: 800
# Range: > 1
ticks_per_item = 800
#How long (in ticks) the full tank of a factoryheart lasts.
# Default: 2400
# Range: > 1
max_ticks = 1600
